name: 'Generate Octoscope Report'
description: 'Generates a github actions usage report using octoscope gh cli extension.'
author: 'noamtamir'
runs:
  using: 'composite'
  steps:
    - name: Install Octoscope gh extension
      run: gh extension install noamtamir/gh-octoscope || echo "Extension already installed"
      shell: bash

    - name: Generate Octoscope Report
      run: gh octoscope report
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
