name: 'Generate Octoscope Report'
description: 'Generates a github actions usage report using octoscope gh cli extension.'
author: 'noamtamir'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token used for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Octoscope gh extension
      run: gh extension install noamtamir/gh-octoscope
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Generate Octoscope Report
      run: gh octoscope report
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
